// =============================================================================
// state/order.states.js — valid states mirror OrderStatus enum in schema
// =============================================================================

export const ORDER_STATES = {
  CREATED: 'CREATED',
  PENDING_APPROVAL: 'PENDING',
  APPROVED: 'CONFIRMED',
  ADVANCE_PENDING: 'PAYMENT_PENDING',
  ADVANCE_PAID: 'ADVANCE_RECEIVED',
  TOKEN_GENERATED: 'TOKEN_GENERATED',
  CARD_DESIGN_READY: 'CARD_DESIGN_READY',
  VENDOR_ASSIGNED: 'SENT_TO_VENDOR',
  PRINTING: 'PRINTING',
  PRINT_COMPLETE: 'PRINT_COMPLETE',
  SHIPPED: 'SHIPPED',
  DELIVERED: 'DELIVERED',
  BALANCE_PENDING: 'BALANCE_PENDING',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  FAILED: 'FAILED',
};

export const STATE_TO_STEP = {
  CREATED: 'CREATE',
  PENDING_APPROVAL: 'CONFIRM',
  APPROVED: 'ADVANCE_INVOICE',
  ADVANCE_PENDING: 'ADVANCE_PAYMENT',
  ADVANCE_PAID: 'TOKEN_GENERATION',
  TOKEN_GENERATED: 'CARD_DESIGN',
  CARD_DESIGN_READY: 'VENDOR_ASSIGNMENT',
  VENDOR_ASSIGNED: 'PRINTING',
  PRINTING: 'SHIPMENT',
  SHIPPED: 'DELIVERY',
  DELIVERED: 'BALANCE_PAYMENT',
  BALANCE_PENDING: 'BALANCE_PAYMENT',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCEL',
  FAILED: 'FAILURE',
};
