// =============================================================================
// events/event.types.js
// =============================================================================

export const ORDER_EVENTS = {
  ORDER_CREATED: "ORDER_CREATED",
  ORDER_APPROVED: "ORDER_APPROVED",
  ADVANCE_PAYMENT_REQUESTED: "ADVANCE_PAYMENT_REQUESTED",
  ADVANCE_PAYMENT_RECEIVED: "ADVANCE_PAYMENT_RECEIVED",
  TOKEN_GENERATED: "TOKEN_GENERATED",
  CARD_GENERATED: "CARD_GENERATED",
  DESIGN_COMPLETED: "DESIGN_COMPLETED",
  VENDOR_ASSIGNED: "VENDOR_ASSIGNED",
  PRINTING_STARTED: "PRINTING_STARTED",
  SHIPPED: "SHIPPED",
  DELIVERED: "DELIVERED",
  ORDER_COMPLETED: "ORDER_COMPLETED",
  ORDER_CANCELLED: "ORDER_CANCELLED",
  STEP_FAILED: "STEP_FAILED",
};

// Maps event → next event in the pipeline (linear chain)
export const EVENT_CHAIN = {
  ORDER_CREATED: ORDER_EVENTS.ORDER_APPROVED, // after approval worker
  ORDER_APPROVED: ORDER_EVENTS.ADVANCE_PAYMENT_REQUESTED,
  ADVANCE_PAYMENT_REQUESTED: ORDER_EVENTS.ADVANCE_PAYMENT_RECEIVED, // triggered by webhook
  ADVANCE_PAYMENT_RECEIVED: ORDER_EVENTS.TOKEN_GENERATED,
  TOKEN_GENERATED: ORDER_EVENTS.CARD_GENERATED,
  CARD_GENERATED: ORDER_EVENTS.DESIGN_COMPLETED,
  DESIGN_COMPLETED: ORDER_EVENTS.VENDOR_ASSIGNED,
  VENDOR_ASSIGNED: ORDER_EVENTS.PRINTING_STARTED,
  PRINTING_STARTED: ORDER_EVENTS.SHIPPED,
  SHIPPED: ORDER_EVENTS.DELIVERED,
  DELIVERED: ORDER_EVENTS.ORDER_COMPLETED,
};
