@baseUrl = http://localhost:3000/api

###! Super Admin Login
POST {{baseUrl}}/auth/super-admin
Content-Type: application/json

{
  "email": "karananimesh144@gmail.com",
  "password": "Karan@144#"
}

###! School Login
POST {{baseUrl}}/auth/school
Content-Type: application/json

{
  "email": "schooladmin@test.com",
  "password": "Admin@123#"
}



###! All logout
POST {{baseUrl}}/auth/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4OWQ0Y2FiOC0xYzFiLTQ0ZWMtYmU1ZC1hNDhmMjgzNDczYWUiLCJyb2xlIjoiU0NIT09MX1VTRVIiLCJzZXNzaW9uSWQiOiJlYTQ5OWYwYy0yMzA3LTQ0MzEtYTk2Yy01YTI5MTljMWUzZmQiLCJzY2hvb2xJZCI6ImVhMjk2MmFlLTBmNWMtNDA0NC1iN2I2LTU2NmJmN2Y5NzMzZiIsImlhdCI6MTc3MzI4OTU1NSwiZXhwIjoxNzczMjkzMTU1LCJhdWQiOiJyZXNxaWQtYXBpIiwiaXNzIjoicmVzcWlkIn0.QoPfRQpr7O6W7h7G6kbH8cVLYzf-DgO0KMQ4P9Y9Z2g

{
  "refreshToken": "e0bd3b9792d67954c4453a592c7c4f9c3fbabd90474097c869608c8e963eba14"
}