// =============================================================================
// orchestrator/events/event.types.js — RESQID (FIXED)
// =============================================================================

export const EVENTS = Object.freeze({
  // ── Emergency ────────────────────────────────────────────────────────────
  EMERGENCY_ALERT_TRIGGERED: 'EMERGENCY_ALERT_TRIGGERED',
  EMERGENCY_ALERT_DELIVERED: 'EMERGENCY_ALERT_DELIVERED',
  EMERGENCY_ALERT_FAILED: 'EMERGENCY_ALERT_FAILED',
  EMERGENCY_ALERT_ESCALATED: 'EMERGENCY_ALERT_ESCALATED',

  // ── Order lifecycle ───────────────────────────────────────────────────────
  ORDER_CREATED: 'ORDER_CREATED',
  ORDER_CONFIRMED: 'ORDER_CONFIRMED',
  ORDER_ADVANCE_INVOICE_ISSUED: 'ORDER_ADVANCE_INVOICE_ISSUED',
  PARTIAL_INVOICE_GENERATED: 'PARTIAL_INVOICE_GENERATED', // ✅ ADDED for dispatcher
  ORDER_ADVANCE_PAYMENT_RECEIVED: 'ORDER_ADVANCE_PAYMENT_RECEIVED',
  PARTIAL_PAYMENT_CONFIRMED: 'PARTIAL_PAYMENT_CONFIRMED', // ✅ ADDED for dispatcher
  ORDER_TOKEN_GENERATION_STARTED: 'ORDER_TOKEN_GENERATION_STARTED',
  ORDER_TOKEN_GENERATION_COMPLETE: 'ORDER_TOKEN_GENERATION_COMPLETE',
  ORDER_CARD_DESIGN_STARTED: 'ORDER_CARD_DESIGN_STARTED',
  ORDER_CARD_DESIGN_COMPLETE: 'ORDER_CARD_DESIGN_COMPLETE',
  ORDER_PDF_GENERATED: 'ORDER_PDF_GENERATED',
  ORDER_SENT_TO_VENDOR: 'ORDER_SENT_TO_VENDOR',
  ORDER_PRINTING_STARTED: 'ORDER_PRINTING_STARTED',
  ORDER_PRINTING_COMPLETE: 'ORDER_PRINTING_COMPLETE',
  ORDER_READY_TO_SHIP: 'ORDER_READY_TO_SHIP', // ✅ ADDED
  ORDER_SHIPPED: 'ORDER_SHIPPED',
  ORDER_OUT_FOR_DELIVERY: 'ORDER_OUT_FOR_DELIVERY',
  ORDER_DELIVERED: 'ORDER_DELIVERED',
  ORDER_BALANCE_INVOICE_ISSUED: 'ORDER_BALANCE_INVOICE_ISSUED',
  ORDER_BALANCE_PAYMENT_RECEIVED: 'ORDER_BALANCE_PAYMENT_RECEIVED',
  ORDER_COMPLETED: 'ORDER_COMPLETED',
  ORDER_CANCELLED: 'ORDER_CANCELLED',
  ORDER_REFUNDED: 'ORDER_REFUNDED',
  ORDER_ON_HOLD: 'ORDER_ON_HOLD',
  DESIGN_APPROVED: 'DESIGN_APPROVED', // ✅ ADDED for dispatcher

  // ── Auth / User ───────────────────────────────────────────────────────────
  USER_OTP_REQUESTED: 'USER_OTP_REQUESTED',
  USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  USER_DEVICE_LOGIN_NEW: 'USER_DEVICE_LOGIN_NEW',
  USER_PASSWORD_RESET_REQUESTED: 'USER_PASSWORD_RESET_REQUESTED',

  // ── School ────────────────────────────────────────────────────────────────
  SCHOOL_ONBOARDED: 'SCHOOL_ONBOARDED',
  SCHOOL_RENEWAL_DUE: 'SCHOOL_RENEWAL_DUE',
  SCHOOL_RENEWAL_COMPLETED: 'SCHOOL_RENEWAL_COMPLETED',

  // ── Student ───────────────────────────────────────────────────────────────
  STUDENT_REGISTERED: 'STUDENT_REGISTERED',
  STUDENT_QR_SCANNED: 'STUDENT_QR_SCANNED',
  STUDENT_CARD_ACTIVATED: 'STUDENT_CARD_ACTIVATED',
  STUDENT_CARD_DEACTIVATED: 'STUDENT_CARD_DEACTIVATED',
  STUDENT_CARD_EXPIRING: 'STUDENT_CARD_EXPIRING',

  // app announcement
  FESTIVAL_WISH_BROADCAST: 'FESTIVAL_WISH_BROADCAST',
  GOVT_ALERT_BROADCAST: 'GOVT_ALERT_BROADCAST',
  SERVER_MAINTENANCE: 'SERVER_MAINTENANCE',

  // ── System ────────────────────────────────────────────────────────────────
  WORKER_JOB_FAILED: 'WORKER_JOB_FAILED',
  WORKER_JOB_DEAD: 'WORKER_JOB_DEAD',
  SYSTEM_HEALTH_DEGRADED: 'SYSTEM_HEALTH_DEGRADED',
});
